function TEST = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  TEST = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  TEST = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  TEST = importfile("C:\Users\pkth002\Documents\Object_Detection\Data\TEST.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Dec-2021 04:49:37

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["filename", "label"];
opts.VariableTypes = ["char", "char"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["filename", "label"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["filename", "label"], "EmptyFieldRule", "auto");

% Import the data
TEST = readtable(filename, opts);

end